# ! [doc = r" Auto-generated Axum server from OpenAPI specification"] 
# ! [doc = r" Generated by openapi-to-axum"] 

use axum :: { routing :: { get , post } , Router , Json , extract :: Path , } ; 
use serde :: { Deserialize , Serialize } ; 
use std :: net :: SocketAddr ; # [derive (Debug , Deserialize , Serialize)] 

pub struct Pet 
{ pub id : serde_json :: Value , 
    pub tag : Option < serde_json :: Value > , 
    pub name : serde_json :: Value 
} 

async fn handle_get__pets () -> & 'static str { "Hello, World!" } 

async fn handle_post__pets () -> & 'static str { "Hello, World!" } 

# [doc = r" Create the Axum router with all generated routes"] 

pub fn create_app () -> Router 
{ 
    Router :: new () 
    . route ("/pets" , get (handle_get__pets)) 
    . route ("/pets" , post (handle_post__pets)) } 

# [doc = r" Start the server on the given address"] 

pub async fn start_server (addr : SocketAddr) -> Result < () , Box < dyn std :: error :: Error >> 
{ 
    let app = create_app () ; 
    println ! ("🚀 Server starting on {}" , addr) ; 
    axum :: serve (tokio :: net :: TcpListener :: bind (addr) . await ? , app) . await . map_err (| e | e . into ()) 
}