openapi: "3.0.0"
info:
  title: "Pet Store API"
  version: "1.0.0"
paths:
  /pets:
    get:
      operationId: "listPets"
      summary: "List all pets"
      responses:
        "200":
          description: "A list of pets"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Pet"
    post:
      operationId: "createPet"
      summary: "Create a pet"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "201":
          description: "Created"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
